import type { Config } from "tailwindcss";

/**
 * La estética la definen los Figmas, no Tailwind.
 * - Colores primitivos: neutral, primary-1, secondary-1/2/3, opacity-*, system-*
 *   (cambian con data-brand: euro600 | bankinter).
 * - Colores semánticos: namespace "sem-" (cambian con data-theme).
 *   Ej: bg-sem-backgrounds-base · text-sem-texts-base · border-sem-strokes-icons-base
 * Todos referencian las CSS custom properties de src/index.css.
 */
const config: Config = {
  content: ["./src/**/*.{ts,tsx,mdx}", "./.storybook/**/*.{ts,tsx}"],
  theme: {
    screens: {
        "sm": "480px",
        "m": "768px",
        "lg": "1024px",
        "xl": "1440px",
        "xxl": "1620px",
        "xxxl": "1920px",
    },
    extend: {
      spacing: {
        "fx-0": "2px",
        "fx-1": "4px",
        "fx-2": "8px",
        "fx-3": "12px",
        "fx-4": "16px",
        "fx-5": "20px",
        "fx-6": "24px",
        "fx-7": "28px",
        "fx-8": "32px",
        "fx-9": "40px",
        "sp-0": "var(--space-0)",
        "sp-1": "var(--space-1)",
        "sp-2": "var(--space-2)",
        "sp-3": "var(--space-3)",
        "sp-4": "var(--space-4)",
        "sp-5": "var(--space-5)",
        "sp-6": "var(--space-6)",
        "sp-7": "var(--space-7)",
        "sp-8": "var(--space-8)",
        "sp-9": "var(--space-9)",
        "sp-10": "var(--space-10)",
        "sp-11": "var(--space-11)",
        "sp-12": "var(--space-12)",
        "sp-13": "var(--space-13)",
        "sp-14": "var(--space-14)",
        "sp-15": "var(--space-15)",
        "sp-16": "var(--space-16)",
        "sp-17": "var(--space-17)",
        "sp-18": "var(--space-18)",
        "wrapper-default": "var(--wrapper-default)",
        "wrapper-header": "var(--wrapper-header)",
        "wrapper-modal": "var(--wrapper-modal)",
        "wrapper-full": "var(--wrapper-full)",
        "gutter": "var(--gutter)",
      },
      borderRadius: {
        "xxs": "var(--radius-xxs)",
        "xs": "var(--radius-xs)",
        "s": "var(--radius-s)",
        "m": "var(--radius-m)",
        "l": "var(--radius-l)",
        "xl": "var(--radius-xl)",
        "rounded": "var(--radius-rounded)",
        "none": "var(--radius-none)",
      },
      fontFamily: {
        geist: ["Geist", "system-ui", "sans-serif"],
        sans: ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "title-07": ["104px", { lineHeight: "132px", letterSpacing: "-0.8px" }],
        "title-06": ["72px", { lineHeight: "72px", letterSpacing: "-0.8px" }],
        "title-05": ["60px", { lineHeight: "60px", letterSpacing: "-0.8px" }],
        "title-04": ["48px", { lineHeight: "48px", letterSpacing: "-0.8px" }],
        "title-03": ["42px", { lineHeight: "40px", letterSpacing: "-0.8px" }],
        "title-02": ["32px", { lineHeight: "40px", letterSpacing: "-0.8px" }],
        "title-01": ["24px", { lineHeight: "34px", letterSpacing: "-0.8px" }],
        "body-06": ["26px", { lineHeight: "38px", letterSpacing: "0px" }],
        "body-05": ["22px", { lineHeight: "32px", letterSpacing: "0px" }],
        "body-04": ["20px", { lineHeight: "28px", letterSpacing: "0px" }],
        "body-03": ["16px", { lineHeight: "24px", letterSpacing: "0px" }],
        "body-02": ["14px", { lineHeight: "22px", letterSpacing: "0px" }],
        "body-01": ["12px", { lineHeight: "18px", letterSpacing: "0px" }],
        "labels-01": ["10px", { lineHeight: "14px", letterSpacing: "0.5px" }],
        "labels-02": ["12px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "cta-03": ["18px", { lineHeight: "18px", letterSpacing: "0px" }],
        "cta-02": ["16px", { lineHeight: "16px", letterSpacing: "0px" }],
        "cta-01": ["14px", { lineHeight: "14px", letterSpacing: "0px" }],
        "cta-link-footer-02": ["16px", { lineHeight: "16px", letterSpacing: "0px" }],
        "cta-link-footer-01": ["14px", { lineHeight: "12px", letterSpacing: "0px" }],
        "forms-input-m-text": ["18px", { lineHeight: "24px", letterSpacing: "0px" }],
        "forms-input-m-label-in": ["10px", { lineHeight: "14px", letterSpacing: "0px" }],
        "forms-input-m-label-out": ["16px", { lineHeight: "16px", letterSpacing: "0px" }],
        "forms-input-m-info": ["14px", { lineHeight: "14px", letterSpacing: "0px" }],
        "forms-input-s-text": ["14px", { lineHeight: "14px", letterSpacing: "0px" }],
        "forms-input-s-label-in": ["10px", { lineHeight: "12px", letterSpacing: "0px" }],
        "forms-input-s-label-out": ["14px", { lineHeight: "14px", letterSpacing: "0px" }],
        "forms-input-s-info": ["12px", { lineHeight: "12px", letterSpacing: "0px" }],
      },
      letterSpacing: {
        "title": "-0.8px",
        "body": "0px",
        "label": "0.5px",
        "cta": "0px",
        "forms": "0px",
      },
      colors: {
        "neutral": {
          "white": "var(--color-neutral-white)",
          "98": "var(--color-neutral-98)",
          "96": "var(--color-neutral-96)",
          "94": "var(--color-neutral-94)",
          "90": "var(--color-neutral-90)",
          "80": "var(--color-neutral-80)",
          "70": "var(--color-neutral-70)",
          "60": "var(--color-neutral-60)",
          "50": "var(--color-neutral-50)",
          "40": "var(--color-neutral-40)",
          "30": "var(--color-neutral-30)",
          "20": "var(--color-neutral-20)",
          "10": "var(--color-neutral-10)",
          "black": "var(--color-neutral-black)",
        },
        "primary-1": {
          "100": "var(--color-primary-1-100)",
          "98": "var(--color-primary-1-98)",
          "96": "var(--color-primary-1-96)",
          "94": "var(--color-primary-1-94)",
          "90": "var(--color-primary-1-90)",
          "80": "var(--color-primary-1-80)",
          "70": "var(--color-primary-1-70)",
          "60": "var(--color-primary-1-60)",
          "50": "var(--color-primary-1-50)",
          "40": "var(--color-primary-1-40)",
          "30": "var(--color-primary-1-30)",
          "20": "var(--color-primary-1-20)",
          "10": "var(--color-primary-1-10)",
          "0": "var(--color-primary-1-0)",
        },
        "secondary-1": {
          "100": "var(--color-secondary-1-100)",
          "98": "var(--color-secondary-1-98)",
          "96": "var(--color-secondary-1-96)",
          "94": "var(--color-secondary-1-94)",
          "90": "var(--color-secondary-1-90)",
          "80": "var(--color-secondary-1-80)",
          "70": "var(--color-secondary-1-70)",
          "60": "var(--color-secondary-1-60)",
          "50": "var(--color-secondary-1-50)",
          "40": "var(--color-secondary-1-40)",
          "30": "var(--color-secondary-1-30)",
          "20": "var(--color-secondary-1-20)",
          "10": "var(--color-secondary-1-10)",
          "0": "var(--color-secondary-1-0)",
        },
        "secondary-2": {
          "100": "var(--color-secondary-2-100)",
          "98": "var(--color-secondary-2-98)",
          "96": "var(--color-secondary-2-96)",
          "94": "var(--color-secondary-2-94)",
          "90": "var(--color-secondary-2-90)",
          "80": "var(--color-secondary-2-80)",
          "70": "var(--color-secondary-2-70)",
          "60": "var(--color-secondary-2-60)",
          "50": "var(--color-secondary-2-50)",
          "40": "var(--color-secondary-2-40)",
          "30": "var(--color-secondary-2-30)",
          "20": "var(--color-secondary-2-20)",
          "10": "var(--color-secondary-2-10)",
          "0": "var(--color-secondary-2-0)",
        },
        "secondary-3": {
          "100": "var(--color-secondary-3-100)",
          "98": "var(--color-secondary-3-98)",
          "96": "var(--color-secondary-3-96)",
          "94": "var(--color-secondary-3-94)",
          "90": "var(--color-secondary-3-90)",
          "80": "var(--color-secondary-3-80)",
          "70": "var(--color-secondary-3-70)",
          "60": "var(--color-secondary-3-60)",
          "50": "var(--color-secondary-3-50)",
          "40": "var(--color-secondary-3-40)",
          "30": "var(--color-secondary-3-30)",
          "20": "var(--color-secondary-3-20)",
          "10": "var(--color-secondary-3-10)",
          "0": "var(--color-secondary-3-0)",
        },
        "opacity-black": {
          "100": "var(--color-opacity-black-100)",
          "98": "var(--color-opacity-black-98)",
          "96": "var(--color-opacity-black-96)",
          "94": "var(--color-opacity-black-94)",
          "90": "var(--color-opacity-black-90)",
          "80": "var(--color-opacity-black-80)",
          "70": "var(--color-opacity-black-70)",
          "60": "var(--color-opacity-black-60)",
          "50": "var(--color-opacity-black-50)",
          "40": "var(--color-opacity-black-40)",
          "30": "var(--color-opacity-black-30)",
          "20": "var(--color-opacity-black-20)",
          "10": "var(--color-opacity-black-10)",
          "0": "var(--color-opacity-black-0)",
        },
        "opacity-white": {
          "100": "var(--color-opacity-white-100)",
          "98": "var(--color-opacity-white-98)",
          "96": "var(--color-opacity-white-96)",
          "94": "var(--color-opacity-white-94)",
          "90": "var(--color-opacity-white-90)",
          "80": "var(--color-opacity-white-80)",
          "70": "var(--color-opacity-white-70)",
          "60": "var(--color-opacity-white-60)",
          "50": "var(--color-opacity-white-50)",
          "40": "var(--color-opacity-white-40)",
          "30": "var(--color-opacity-white-30)",
          "20": "var(--color-opacity-white-20)",
          "10": "var(--color-opacity-white-10)",
          "0": "var(--color-opacity-white-0)",
        },
        "system-error": {
          "01": "var(--color-system-error-01)",
          "02": "var(--color-system-error-02)",
          "03": "var(--color-system-error-03)",
        },
        "system-success": {
          "01": "var(--color-system-success-01)",
          "02": "var(--color-system-success-02)",
          "03": "var(--color-system-success-03)",
        },
        "system-warning": {
          "01": "var(--color-system-warning-01)",
          "02": "var(--color-system-warning-02)",
          "03": "var(--color-system-warning-03)",
        },
        "sem": {
          "backgrounds-base": "var(--sem-backgrounds-base)",
          "backgrounds-neutral-1": "var(--sem-backgrounds-neutral-1)",
          "backgrounds-neutral-2": "var(--sem-backgrounds-neutral-2)",
          "backgrounds-neutral-3": "var(--sem-backgrounds-neutral-3)",
          "backgrounds-white": "var(--sem-backgrounds-white)",
          "backgrounds-inverse": "var(--sem-backgrounds-inverse)",
          "backgrounds-overlay": "var(--sem-backgrounds-overlay)",
          "backgrounds-accent-base": "var(--sem-backgrounds-accent-base)",
          "backgrounds-accent-1": "var(--sem-backgrounds-accent-1)",
          "backgrounds-accent-2": "var(--sem-backgrounds-accent-2)",
          "backgrounds-accent-3": "var(--sem-backgrounds-accent-3)",
          "backgrounds-accent-4": "var(--sem-backgrounds-accent-4)",
          "backgrounds-success-1": "var(--sem-backgrounds-success-1)",
          "backgrounds-success-2": "var(--sem-backgrounds-success-2)",
          "backgrounds-success-3": "var(--sem-backgrounds-success-3)",
          "backgrounds-error-1": "var(--sem-backgrounds-error-1)",
          "backgrounds-error-2": "var(--sem-backgrounds-error-2)",
          "backgrounds-error-3": "var(--sem-backgrounds-error-3)",
          "backgrounds-warning-1": "var(--sem-backgrounds-warning-1)",
          "backgrounds-warning-2": "var(--sem-backgrounds-warning-2)",
          "backgrounds-warning-3": "var(--sem-backgrounds-warning-3)",
          "backgrounds-always-white": "var(--sem-backgrounds-always-white)",
          "backgrounds-always-black": "var(--sem-backgrounds-always-black)",
          "backgrounds-hover": "var(--sem-backgrounds-hover)",
          "backgrounds-disabled": "var(--sem-backgrounds-disabled)",
          "backgrounds-selected": "var(--sem-backgrounds-selected)",
          "texts-base": "var(--sem-texts-base)",
          "strokes-icons-base": "var(--sem-strokes-icons-base)",
          "button-primary-default-fill": "var(--sem-button-primary-default-fill)",
          "button-primary-default-stroke": "var(--sem-button-primary-default-stroke)",
          "button-primary-default-text": "var(--sem-button-primary-default-text)",
          "button-primary-default-icon": "var(--sem-button-primary-default-icon)",
          "button-primary-hover-fill": "var(--sem-button-primary-hover-fill)",
          "button-primary-hover-stroke": "var(--sem-button-primary-hover-stroke)",
          "button-primary-hover-text": "var(--sem-button-primary-hover-text)",
          "button-primary-hover-icon": "var(--sem-button-primary-hover-icon)",
          "button-primary-selected-fill": "var(--sem-button-primary-selected-fill)",
          "button-primary-selected-stroke": "var(--sem-button-primary-selected-stroke)",
          "button-primary-selected-text": "var(--sem-button-primary-selected-text)",
          "button-primary-selected-icon": "var(--sem-button-primary-selected-icon)",
          "button-primary-disabled-fill": "var(--sem-button-primary-disabled-fill)",
          "button-primary-disabled-stroke": "var(--sem-button-primary-disabled-stroke)",
          "button-primary-disabled-text": "var(--sem-button-primary-disabled-text)",
          "button-primary-disabled-icon": "var(--sem-button-primary-disabled-icon)",
          "button-secondary-default-fill": "var(--sem-button-secondary-default-fill)",
          "button-secondary-default-stroke": "var(--sem-button-secondary-default-stroke)",
          "button-secondary-default-text": "var(--sem-button-secondary-default-text)",
          "button-secondary-default-icon": "var(--sem-button-secondary-default-icon)",
          "button-secondary-hover-fill": "var(--sem-button-secondary-hover-fill)",
          "button-secondary-hover-stroke": "var(--sem-button-secondary-hover-stroke)",
          "button-secondary-hover-text": "var(--sem-button-secondary-hover-text)",
          "button-secondary-hover-icon": "var(--sem-button-secondary-hover-icon)",
          "button-secondary-focused-fill": "var(--sem-button-secondary-focused-fill)",
          "button-secondary-focused-stroke": "var(--sem-button-secondary-focused-stroke)",
          "button-secondary-focused-text": "var(--sem-button-secondary-focused-text)",
          "button-secondary-focused-icon": "var(--sem-button-secondary-focused-icon)",
          "button-secondary-selected-fill": "var(--sem-button-secondary-selected-fill)",
          "button-secondary-selected-stroke": "var(--sem-button-secondary-selected-stroke)",
          "button-secondary-selected-text": "var(--sem-button-secondary-selected-text)",
          "button-secondary-selected-icon": "var(--sem-button-secondary-selected-icon)",
          "button-secondary-disabled-fill": "var(--sem-button-secondary-disabled-fill)",
          "button-secondary-disabled-stroke": "var(--sem-button-secondary-disabled-stroke)",
          "button-secondary-disabled-text": "var(--sem-button-secondary-disabled-text)",
          "button-secondary-disabled-icon": "var(--sem-button-secondary-disabled-icon)",
          "button-terciary-default-fill": "var(--sem-button-terciary-default-fill)",
          "button-terciary-default-stroke": "var(--sem-button-terciary-default-stroke)",
          "button-terciary-default-text": "var(--sem-button-terciary-default-text)",
          "button-terciary-default-icon": "var(--sem-button-terciary-default-icon)",
          "button-terciary-hover-fill": "var(--sem-button-terciary-hover-fill)",
          "button-terciary-hover-stroke": "var(--sem-button-terciary-hover-stroke)",
          "button-terciary-hover-text": "var(--sem-button-terciary-hover-text)",
          "button-terciary-hover-icon": "var(--sem-button-terciary-hover-icon)",
          "button-terciary-focused-fill": "var(--sem-button-terciary-focused-fill)",
          "button-terciary-focused-stroke": "var(--sem-button-terciary-focused-stroke)",
          "button-terciary-focused-text": "var(--sem-button-terciary-focused-text)",
          "button-terciary-focused-icon": "var(--sem-button-terciary-focused-icon)",
          "button-terciary-selected-fill": "var(--sem-button-terciary-selected-fill)",
          "button-terciary-selected-stroke": "var(--sem-button-terciary-selected-stroke)",
          "button-terciary-selected-text": "var(--sem-button-terciary-selected-text)",
          "button-terciary-selected-icon": "var(--sem-button-terciary-selected-icon)",
          "button-terciary-disabled-fill": "var(--sem-button-terciary-disabled-fill)",
          "button-terciary-disabled-stroke": "var(--sem-button-terciary-disabled-stroke)",
          "button-terciary-disabled-text": "var(--sem-button-terciary-disabled-text)",
          "button-terciary-disabled-icon": "var(--sem-button-terciary-disabled-icon)",
          "forms-default-fill": "var(--sem-forms-default-fill)",
          "forms-default-stroke": "var(--sem-forms-default-stroke)",
          "forms-default-text": "var(--sem-forms-default-text)",
          "forms-default-label-out": "var(--sem-forms-default-label-out)",
          "forms-default-label-in": "var(--sem-forms-default-label-in)",
          "forms-default-icon": "var(--sem-forms-default-icon)",
          "forms-default-message": "var(--sem-forms-default-message)",
          "forms-hover-fill": "var(--sem-forms-hover-fill)",
          "forms-hover-stroke": "var(--sem-forms-hover-stroke)",
          "forms-hover-text": "var(--sem-forms-hover-text)",
          "forms-hover-label-out": "var(--sem-forms-hover-label-out)",
          "forms-hover-label-in": "var(--sem-forms-hover-label-in)",
          "forms-hover-icon": "var(--sem-forms-hover-icon)",
          "forms-hover-message": "var(--sem-forms-hover-message)",
          "forms-focused-fill": "var(--sem-forms-focused-fill)",
          "forms-filled-fill": "var(--sem-forms-filled-fill)",
          "forms-filled-stroke": "var(--sem-forms-filled-stroke)",
          "forms-filled-text": "var(--sem-forms-filled-text)",
          "forms-filled-label-out": "var(--sem-forms-filled-label-out)",
          "forms-filled-label-in": "var(--sem-forms-filled-label-in)",
          "forms-filled-icon": "var(--sem-forms-filled-icon)",
          "forms-filled-message": "var(--sem-forms-filled-message)",
          "forms-focused-stroke": "var(--sem-forms-focused-stroke)",
          "forms-focused-stroke-box": "var(--sem-forms-focused-stroke-box)",
          "forms-focused-text": "var(--sem-forms-focused-text)",
          "forms-focused-label-out": "var(--sem-forms-focused-label-out)",
          "forms-focused-label-in": "var(--sem-forms-focused-label-in)",
          "forms-focused-icon": "var(--sem-forms-focused-icon)",
          "forms-focused-message": "var(--sem-forms-focused-message)",
          "forms-error-fill": "var(--sem-forms-error-fill)",
          "forms-error-stroke": "var(--sem-forms-error-stroke)",
          "forms-error-text": "var(--sem-forms-error-text)",
          "forms-error-label-out": "var(--sem-forms-error-label-out)",
          "forms-error-label-in": "var(--sem-forms-error-label-in)",
          "forms-error-icon": "var(--sem-forms-error-icon)",
          "forms-error-message": "var(--sem-forms-error-message)",
          "forms-validated-fill": "var(--sem-forms-validated-fill)",
          "forms-validated-stroke": "var(--sem-forms-validated-stroke)",
          "forms-validated-text": "var(--sem-forms-validated-text)",
          "forms-validated-label-out": "var(--sem-forms-validated-label-out)",
          "forms-validated-label-in": "var(--sem-forms-validated-label-in)",
          "forms-validated-icon": "var(--sem-forms-validated-icon)",
          "forms-validated-message": "var(--sem-forms-validated-message)",
          "forms-disabled-fill": "var(--sem-forms-disabled-fill)",
          "forms-disabled-stroke": "var(--sem-forms-disabled-stroke)",
          "forms-disabled-text": "var(--sem-forms-disabled-text)",
          "forms-disabled-label-out": "var(--sem-forms-disabled-label-out)",
          "forms-disabled-label-in": "var(--sem-forms-disabled-label-in)",
          "forms-disabled-icon": "var(--sem-forms-disabled-icon)",
          "forms-disabled-message": "var(--sem-forms-disabled-message)",
          "forms-selected-fill": "var(--sem-forms-selected-fill)",
          "forms-selected-stroke": "var(--sem-forms-selected-stroke)",
          "forms-selected-text": "var(--sem-forms-selected-text)",
          "forms-selected-label-out": "var(--sem-forms-selected-label-out)",
          "forms-selected-label-in": "var(--sem-forms-selected-label-in)",
          "forms-selected-icon": "var(--sem-forms-selected-icon)",
          "forms-selected-message": "var(--sem-forms-selected-message)",
          "button-primary-focused-fill": "var(--sem-button-primary-focused-fill)",
          "button-primary-focused-stroke": "var(--sem-button-primary-focused-stroke)",
          "button-primary-focused-text": "var(--sem-button-primary-focused-text)",
          "button-primary-focused-icon": "var(--sem-button-primary-focused-icon)",
          "strokes-icons-neutral-1": "var(--sem-strokes-icons-neutral-1)",
          "strokes-icons-neutral-2": "var(--sem-strokes-icons-neutral-2)",
          "strokes-icons-neutral-3": "var(--sem-strokes-icons-neutral-3)",
          "strokes-icons-neutral-4": "var(--sem-strokes-icons-neutral-4)",
          "strokes-icons-inverse": "var(--sem-strokes-icons-inverse)",
          "strokes-icons-accent-base": "var(--sem-strokes-icons-accent-base)",
          "strokes-icons-accent-1": "var(--sem-strokes-icons-accent-1)",
          "strokes-icons-accent-2": "var(--sem-strokes-icons-accent-2)",
          "strokes-icons-accent-3": "var(--sem-strokes-icons-accent-3)",
          "strokes-icons-accent-4": "var(--sem-strokes-icons-accent-4)",
          "strokes-icons-secondary-base": "var(--sem-strokes-icons-secondary-base)",
          "strokes-icons-secondary-1": "var(--sem-strokes-icons-secondary-1)",
          "strokes-icons-secondary-2": "var(--sem-strokes-icons-secondary-2)",
          "strokes-icons-secondary-3": "var(--sem-strokes-icons-secondary-3)",
          "strokes-icons-secondary-4": "var(--sem-strokes-icons-secondary-4)",
          "strokes-icons-success-1": "var(--sem-strokes-icons-success-1)",
          "strokes-icons-success-2": "var(--sem-strokes-icons-success-2)",
          "strokes-icons-success-3": "var(--sem-strokes-icons-success-3)",
          "strokes-icons-error-1": "var(--sem-strokes-icons-error-1)",
          "strokes-icons-error-2": "var(--sem-strokes-icons-error-2)",
          "strokes-icons-error-3": "var(--sem-strokes-icons-error-3)",
          "strokes-icons-warning-1": "var(--sem-strokes-icons-warning-1)",
          "strokes-icons-warning-2": "var(--sem-strokes-icons-warning-2)",
          "strokes-icons-warning-3": "var(--sem-strokes-icons-warning-3)",
          "texts-neutral-1": "var(--sem-texts-neutral-1)",
          "texts-neutral-2": "var(--sem-texts-neutral-2)",
          "texts-neutral-3": "var(--sem-texts-neutral-3)",
          "texts-inverted": "var(--sem-texts-inverted)",
          "texts-accent-base": "var(--sem-texts-accent-base)",
          "texts-accent-1": "var(--sem-texts-accent-1)",
          "texts-accent-2": "var(--sem-texts-accent-2)",
          "texts-secondary-base": "var(--sem-texts-secondary-base)",
          "texts-secondary-1": "var(--sem-texts-secondary-1)",
          "texts-secondary-2": "var(--sem-texts-secondary-2)",
          "texts-error": "var(--sem-texts-error)",
          "texts-success": "var(--sem-texts-success)",
          "texts-warning": "var(--sem-texts-warning)",
          "texts-link": "var(--sem-texts-link)",
          "texts-always-black": "var(--sem-texts-always-black)",
          "texts-always-white": "var(--sem-texts-always-white)",
          "texts-hover": "var(--sem-texts-hover)",
          "texts-disabled": "var(--sem-texts-disabled)",
          "button-link-primary-default-fill": "var(--sem-button-link-primary-default-fill)",
          "button-link-primary-default-stroke": "var(--sem-button-link-primary-default-stroke)",
          "button-link-primary-default-text": "var(--sem-button-link-primary-default-text)",
          "button-link-primary-default-icon": "var(--sem-button-link-primary-default-icon)",
          "button-link-primary-hover-fill": "var(--sem-button-link-primary-hover-fill)",
          "button-link-primary-hover-stroke": "var(--sem-button-link-primary-hover-stroke)",
          "button-link-primary-hover-text": "var(--sem-button-link-primary-hover-text)",
          "button-link-primary-hover-icon": "var(--sem-button-link-primary-hover-icon)",
          "button-link-primary-focused-fill": "var(--sem-button-link-primary-focused-fill)",
          "button-link-primary-focused-stroke": "var(--sem-button-link-primary-focused-stroke)",
          "button-link-primary-focused-text": "var(--sem-button-link-primary-focused-text)",
          "button-link-primary-focused-icon": "var(--sem-button-link-primary-focused-icon)",
          "button-link-primary-selected-fill": "var(--sem-button-link-primary-selected-fill)",
          "button-link-primary-selected-stroke": "var(--sem-button-link-primary-selected-stroke)",
          "button-link-primary-selected-text": "var(--sem-button-link-primary-selected-text)",
          "button-link-primary-selected-icon": "var(--sem-button-link-primary-selected-icon)",
          "button-link-primary-disabled-fill": "var(--sem-button-link-primary-disabled-fill)",
          "button-link-primary-disabled-stroke": "var(--sem-button-link-primary-disabled-stroke)",
          "button-link-primary-disabled-text": "var(--sem-button-link-primary-disabled-text)",
          "button-link-primary-disabled-icon": "var(--sem-button-link-primary-disabled-icon)",
          "forms-undefined-fill": "var(--sem-forms-undefined-fill)",
          "forms-undefined-stroke": "var(--sem-forms-undefined-stroke)",
          "forms-undefined-text": "var(--sem-forms-undefined-text)",
          "forms-undefined-label-out": "var(--sem-forms-undefined-label-out)",
          "forms-undefined-label-in": "var(--sem-forms-undefined-label-in)",
          "forms-undefined-icon": "var(--sem-forms-undefined-icon)",
          "forms-undefined-message": "var(--sem-forms-undefined-message)",        },
      },
    },
  },
  plugins: [],
};

export default config;
