import type { Config } from "tailwindcss";

/**
 * La estética la definen los Figmas, no Tailwind.
 * Los colores referencian las CSS custom properties primitivas de src/index.css
 * (generadas desde la colección "Primitives" del Figma). Cambiar de marca con
 * el atributo data-brand en <html>.
 */
const config: Config = {
  content: ["./src/**/*.{ts,tsx,mdx}", "./.storybook/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "neutral": {
          "white": "var(--color-neutral-white)",
          "98": "var(--color-neutral-98)",
          "96": "var(--color-neutral-96)",
          "94": "var(--color-neutral-94)",
          "90": "var(--color-neutral-90)",
          "80": "var(--color-neutral-80)",
          "70": "var(--color-neutral-70)",
          "60": "var(--color-neutral-60)",
          "50": "var(--color-neutral-50)",
          "40": "var(--color-neutral-40)",
          "30": "var(--color-neutral-30)",
          "20": "var(--color-neutral-20)",
          "10": "var(--color-neutral-10)",
          "black": "var(--color-neutral-black)",
        },
        "primary-1": {
          "100": "var(--color-primary-1-100)",
          "98": "var(--color-primary-1-98)",
          "96": "var(--color-primary-1-96)",
          "94": "var(--color-primary-1-94)",
          "90": "var(--color-primary-1-90)",
          "80": "var(--color-primary-1-80)",
          "70": "var(--color-primary-1-70)",
          "60": "var(--color-primary-1-60)",
          "50": "var(--color-primary-1-50)",
          "40": "var(--color-primary-1-40)",
          "30": "var(--color-primary-1-30)",
          "20": "var(--color-primary-1-20)",
          "10": "var(--color-primary-1-10)",
          "0": "var(--color-primary-1-0)",
        },
        "secondary-1": {
          "100": "var(--color-secondary-1-100)",
          "98": "var(--color-secondary-1-98)",
          "96": "var(--color-secondary-1-96)",
          "94": "var(--color-secondary-1-94)",
          "90": "var(--color-secondary-1-90)",
          "80": "var(--color-secondary-1-80)",
          "70": "var(--color-secondary-1-70)",
          "60": "var(--color-secondary-1-60)",
          "50": "var(--color-secondary-1-50)",
          "40": "var(--color-secondary-1-40)",
          "30": "var(--color-secondary-1-30)",
          "20": "var(--color-secondary-1-20)",
          "10": "var(--color-secondary-1-10)",
          "0": "var(--color-secondary-1-0)",
        },
        "secondary-2": {
          "100": "var(--color-secondary-2-100)",
          "98": "var(--color-secondary-2-98)",
          "96": "var(--color-secondary-2-96)",
          "94": "var(--color-secondary-2-94)",
          "90": "var(--color-secondary-2-90)",
          "80": "var(--color-secondary-2-80)",
          "70": "var(--color-secondary-2-70)",
          "60": "var(--color-secondary-2-60)",
          "50": "var(--color-secondary-2-50)",
          "40": "var(--color-secondary-2-40)",
          "30": "var(--color-secondary-2-30)",
          "20": "var(--color-secondary-2-20)",
          "10": "var(--color-secondary-2-10)",
          "0": "var(--color-secondary-2-0)",
        },
        "secondary-3": {
          "100": "var(--color-secondary-3-100)",
          "98": "var(--color-secondary-3-98)",
          "96": "var(--color-secondary-3-96)",
          "94": "var(--color-secondary-3-94)",
          "90": "var(--color-secondary-3-90)",
          "80": "var(--color-secondary-3-80)",
          "70": "var(--color-secondary-3-70)",
          "60": "var(--color-secondary-3-60)",
          "50": "var(--color-secondary-3-50)",
          "40": "var(--color-secondary-3-40)",
          "30": "var(--color-secondary-3-30)",
          "20": "var(--color-secondary-3-20)",
          "10": "var(--color-secondary-3-10)",
          "0": "var(--color-secondary-3-0)",
        },
        "opacity-black": {
          "100": "var(--color-opacity-black-100)",
          "98": "var(--color-opacity-black-98)",
          "96": "var(--color-opacity-black-96)",
          "94": "var(--color-opacity-black-94)",
          "90": "var(--color-opacity-black-90)",
          "80": "var(--color-opacity-black-80)",
          "70": "var(--color-opacity-black-70)",
          "60": "var(--color-opacity-black-60)",
          "50": "var(--color-opacity-black-50)",
          "40": "var(--color-opacity-black-40)",
          "30": "var(--color-opacity-black-30)",
          "20": "var(--color-opacity-black-20)",
          "10": "var(--color-opacity-black-10)",
          "0": "var(--color-opacity-black-0)",
        },
        "opacity-white": {
          "100": "var(--color-opacity-white-100)",
          "98": "var(--color-opacity-white-98)",
          "96": "var(--color-opacity-white-96)",
          "94": "var(--color-opacity-white-94)",
          "90": "var(--color-opacity-white-90)",
          "80": "var(--color-opacity-white-80)",
          "70": "var(--color-opacity-white-70)",
          "60": "var(--color-opacity-white-60)",
          "50": "var(--color-opacity-white-50)",
          "40": "var(--color-opacity-white-40)",
          "30": "var(--color-opacity-white-30)",
          "20": "var(--color-opacity-white-20)",
          "10": "var(--color-opacity-white-10)",
          "0": "var(--color-opacity-white-0)",
        },
        "system-error": {
          "01": "var(--color-system-error-01)",
          "02": "var(--color-system-error-02)",
          "03": "var(--color-system-error-03)",
        },
        "system-success": {
          "01": "var(--color-system-success-01)",
          "02": "var(--color-system-success-02)",
          "03": "var(--color-system-success-03)",
        },
        "system-warning": {
          "01": "var(--color-system-warning-01)",
          "02": "var(--color-system-warning-02)",
          "03": "var(--color-system-warning-03)",
        },      },
    },
  },
  plugins: [],
};

export default config;
