/**
 * Tokens de color SEMÁNTICOS — Euro6000 Design System.
 * Fuente: colección "Semantic-Color" del Figma (Euro6000 — Library).
 * 214 tokens · 6 temas. Cada token referencia un primitivo o a otro
 * semántico vía CSS custom properties (--sem-*) en src/index.css.
 *
 * Tema por defecto: "light-white". Cambiar con <html data-theme="...">.
 * NO editar a mano: regenerar desde Figma.
 */

export type SemanticTheme =
  "light-white" | "light-grey" | "dark-red-primary" | "dark-secondary-blue" | "dark-black-brand" | "dark-black-neutral";

export const semanticThemes: { slug: SemanticTheme; label: string }[] = [
  { slug: "light-white", label: "Light - White" },
  { slug: "light-grey", label: "Light - Grey" },
  { slug: "dark-red-primary", label: "Dark - Red - Primary" },
  { slug: "dark-secondary-blue", label: "Dark - Secondary - Blue" },
  { slug: "dark-black-brand", label: "Dark - Black -Brand" },
  { slug: "dark-black-neutral", label: "Dark - Black - Neutral" },
];

/** Devuelve la referencia CSS de un token semántico: cssVar("Backgrounds/Base"). */
export function cssVar(token: string): string {
  const s = token.toLowerCase().replace(/[/ ]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
  return `var(--sem-${s})`;
}

/** Catálogo de tokens semánticos por categoría (nombres tal cual en Figma). */
export const semanticTokenCatalog = {
  "Backgrounds": [
    "Backgrounds/Base",
    "Backgrounds/Neutral-1",
    "Backgrounds/Neutral-2",
    "Backgrounds/Neutral-3",
    "Backgrounds/White",
    "Backgrounds/Inverse",
    "Backgrounds/Overlay",
    "Backgrounds/Accent-Base",
    "Backgrounds/Accent-1",
    "Backgrounds/Accent-2",
    "Backgrounds/Accent-3",
    "Backgrounds/Accent-4",
    "Backgrounds/Success-1",
    "Backgrounds/Success-2",
    "Backgrounds/Success-3",
    "Backgrounds/Error-1",
    "Backgrounds/Error-2",
    "Backgrounds/Error-3",
    "Backgrounds/Warning-1",
    "Backgrounds/Warning-2",
    "Backgrounds/Warning-3",
    "Backgrounds/Always-White",
    "Backgrounds/Always-Black",
    "Backgrounds/Hover",
    "Backgrounds/Disabled",
    "Backgrounds/Selected",
  ],
  "Texts": [
    "Texts/Base",
    "Texts/Neutral 1",
    "Texts/Neutral 2",
    "Texts/Neutral 3",
    "Texts/Inverted",
    "Texts/Accent-Base",
    "Texts/Accent-1",
    "Texts/Accent-2",
    "Texts/Secondary-Base",
    "Texts/Secondary-1",
    "Texts/Secondary-2",
    "Texts/Error",
    "Texts/Success",
    "Texts/Warning",
    "Texts/Link",
    "Texts/Always-Black",
    "Texts/Always-White",
    "Texts/Hover",
    "Texts/Disabled",
  ],
  "Strokes-Icons": [
    "Strokes-Icons/Base",
    "Strokes-Icons/Neutral 1",
    "Strokes-Icons/Neutral 2",
    "Strokes-Icons/Neutral 3",
    "Strokes-Icons/Neutral 4",
    "Strokes-Icons/Inverse",
    "Strokes-Icons/Accent-Base",
    "Strokes-Icons/Accent-1",
    "Strokes-Icons/Accent-2",
    "Strokes-Icons/Accent-3",
    "Strokes-Icons/Accent-4",
    "Strokes-Icons/Secondary-Base",
    "Strokes-Icons/Secondary-1",
    "Strokes-Icons/Secondary-2",
    "Strokes-Icons/Secondary-3",
    "Strokes-Icons/Secondary-4",
    "Strokes-Icons/Success-1",
    "Strokes-Icons/Success-2",
    "Strokes-Icons/Success-3",
    "Strokes-Icons/Error-1",
    "Strokes-Icons/Error-2",
    "Strokes-Icons/Error-3",
    "Strokes-Icons/Warning-1",
    "Strokes-Icons/Warning-2",
    "Strokes-Icons/Warning-3",
  ],
  "Button": [
    "Button/Primary/Default/Fill",
    "Button/Primary/Default/Stroke",
    "Button/Primary/Default/Text",
    "Button/Primary/Default/Icon",
    "Button/Primary/Hover/Fill",
    "Button/Primary/Hover/Stroke",
    "Button/Primary/Hover/Text",
    "Button/Primary/Hover/Icon",
    "Button/Primary/Selected/Fill",
    "Button/Primary/Selected/Stroke",
    "Button/Primary/Selected/Text",
    "Button/Primary/Selected/Icon",
    "Button/Primary/Disabled/Fill",
    "Button/Primary/Disabled/Stroke",
    "Button/Primary/Disabled/Text",
    "Button/Primary/Disabled/Icon",
    "Button/Secondary/Default/Fill",
    "Button/Secondary/Default/Stroke",
    "Button/Secondary/Default/Text",
    "Button/Secondary/Default/Icon",
    "Button/Secondary/Hover/Fill",
    "Button/Secondary/Hover/Stroke",
    "Button/Secondary/Hover/Text",
    "Button/Secondary/Hover/Icon",
    "Button/Secondary/Focused/Fill",
    "Button/Secondary/Focused/Stroke",
    "Button/Secondary/Focused/Text",
    "Button/Secondary/Focused/Icon",
    "Button/Secondary/Selected/Fill",
    "Button/Secondary/Selected/Stroke",
    "Button/Secondary/Selected/Text",
    "Button/Secondary/Selected/Icon",
    "Button/Secondary/Disabled/Fill",
    "Button/Secondary/Disabled/Stroke",
    "Button/Secondary/Disabled/Text",
    "Button/Secondary/Disabled/Icon",
    "Button/Terciary/Default/Fill",
    "Button/Terciary/Default/Stroke",
    "Button/Terciary/Default/Text",
    "Button/Terciary/Default/Icon",
    "Button/Terciary/Hover/Fill",
    "Button/Terciary/Hover/Stroke",
    "Button/Terciary/Hover/Text",
    "Button/Terciary/Hover/Icon",
    "Button/Terciary/Focused/Fill",
    "Button/Terciary/Focused/Stroke",
    "Button/Terciary/Focused/Text",
    "Button/Terciary/Focused/Icon",
    "Button/Terciary/Selected/Fill",
    "Button/Terciary/Selected/Stroke",
    "Button/Terciary/Selected/Text",
    "Button/Terciary/Selected/Icon",
    "Button/Terciary/Disabled/Fill",
    "Button/Terciary/Disabled/Stroke",
    "Button/Terciary/Disabled/Text",
    "Button/Terciary/Disabled/Icon",
    "Button/Primary/Focused/Fill",
    "Button/Primary/Focused/Stroke",
    "Button/Primary/Focused/Text",
    "Button/Primary/Focused/Icon",
    "Button/Link Primary/Default/Fill",
    "Button/Link Primary/Default/Stroke",
    "Button/Link Primary/Default/Text",
    "Button/Link Primary/Default/Icon",
    "Button/Link Primary/Hover/Fill",
    "Button/Link Primary/Hover/Stroke",
    "Button/Link Primary/Hover/Text",
    "Button/Link Primary/Hover/Icon",
    "Button/Link Primary/Focused/Fill",
    "Button/Link Primary/Focused/Stroke",
    "Button/Link Primary/Focused/Text",
    "Button/Link Primary/Focused/Icon",
    "Button/Link Primary/Selected/Fill",
    "Button/Link Primary/Selected/Stroke",
    "Button/Link Primary/Selected/Text",
    "Button/Link Primary/Selected/Icon",
    "Button/Link Primary/Disabled/Fill",
    "Button/Link Primary/Disabled/Stroke",
    "Button/Link Primary/Disabled/Text",
    "Button/Link Primary/Disabled/Icon",
  ],
  "Forms": [
    "Forms/Default/Fill",
    "Forms/Default/Stroke",
    "Forms/Default/Text",
    "Forms/Default/Label-Out",
    "Forms/Default/Label-In",
    "Forms/Default/Icon",
    "Forms/Default/Message",
    "Forms/Hover/Fill",
    "Forms/Hover/Stroke",
    "Forms/Hover/Text",
    "Forms/Hover/Label-Out",
    "Forms/Hover/Label-In",
    "Forms/Hover/Icon",
    "Forms/Hover/Message",
    "Forms/Focused/Fill",
    "Forms/Filled/Fill",
    "Forms/Filled/Stroke",
    "Forms/Filled/Text",
    "Forms/Filled/Label-Out",
    "Forms/Filled/Label-In",
    "Forms/Filled/Icon",
    "Forms/Filled/Message",
    "Forms/Focused/Stroke",
    "Forms/Focused/Stroke-Box",
    "Forms/Focused/Text",
    "Forms/Focused/Label-Out",
    "Forms/Focused/Label-In",
    "Forms/Focused/Icon",
    "Forms/Focused/Message",
    "Forms/Error/Fill",
    "Forms/Error/Stroke",
    "Forms/Error/Text",
    "Forms/Error/Label-Out",
    "Forms/Error/Label-In",
    "Forms/Error/Icon",
    "Forms/Error/Message",
    "Forms/Validated/Fill",
    "Forms/Validated/Stroke",
    "Forms/Validated/Text",
    "Forms/Validated/Label-Out",
    "Forms/Validated/Label-In",
    "Forms/Validated/Icon",
    "Forms/Validated/Message",
    "Forms/Disabled/Fill",
    "Forms/Disabled/Stroke",
    "Forms/Disabled/Text",
    "Forms/Disabled/Label-Out",
    "Forms/Disabled/Label-In",
    "Forms/Disabled/Icon",
    "Forms/Disabled/Message",
    "Forms/Selected/Fill",
    "Forms/Selected/Stroke",
    "Forms/Selected/Text",
    "Forms/Selected/Label-Out",
    "Forms/Selected/Label-In",
    "Forms/Selected/Icon",
    "Forms/Selected/Message",
    "Forms/Undefined/Fill",
    "Forms/Undefined/Stroke",
    "Forms/Undefined/Text",
    "Forms/Undefined/Label-Out",
    "Forms/Undefined/Label-In",
    "Forms/Undefined/Icon",
    "Forms/Undefined/Message",
  ],
} as const;

